### ISSUE TITLE
Unable to install pods

### ISSUE THREAD

**Issue by belkevich** [ClassyKit/Classy#103]
Hi!

`pod install` crashes (see log below) and I unable to build example project. 
Cocoapods version 0.38.2

```
[!] An error occurred while processing the post-install hook of the Podfile.

undefined local variable or method `config' for #<Pod::Podfile:0x007f8a6b0673e8>

/Users/alex/Projects/other/Classy/Podfile:27:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile.rb:170:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile.rb:170:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:764:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:752:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:751:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:155:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by seven77770** [comment]
yeah! same problem!
update cocopod to 0.39.0 still the same.

**Comment by jonah-williams** [comment]
Looks like the `post-install` hook Classy relies on has been deprecated since https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#0230rc1-2013-08-02

While the hook hasn't been removed yet perhaps there's an alternative way to configure gcov so that consumers of the pod do not run into build errors as cocoapods internals change?

If it helps anyone here, these Podfile changes allowed me to run under Cocoapods `0.38.2`: https://github.com/cloudkite/Classy/compare/master...goodeggs:ef258fac27cb4e6d596cb11acc1bc1d2510ed5a2#diff-4a25b996826623c4a3a4910f47f10c30
